name: 💡 Site feature
description: Suggest an improvement to the website (not a new docs topic).
title: '[Feature] '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
