name: PR Automation

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
          
      - name: Check if PR references an issue
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body;
            const issueReference = body.match(/(closes|fixes|resolves)\s+#\d+/i);
            
            if (!issueReference) {
              core.setFailed('PR description must reference an issue using "Fixes #issue-number"');
            }
